### ISSUE TITLE
QuickFix.MessageCracker.Crack() throws QuickFix.UnsupportedMessageType

### ISSUE THREAD

**Issue by matthiasguentert** [mickthompson/QuickFix.CustomMessages#1]
Thanks for this greaste approach to get rid of the ruby code generation dependency. 

**Background:**

- I have have ASP.Net WebApi project targeting .NET Framework 4.7
- I have installed QuickFix.Net (version 1.8.0, by "**Quant Edge JSC**") via nuget
- I have installed QuickFix.CustomMessages (version 1.0.5)
- I have replaced DataDictionary.xml with the one that fits our counterparty 
- Using initiator only side of fix

**Issues & questions I am having:**

1. Am I using the correct QuickFix Nuget package? There are many out there...

2. When the response messages are hitting `this.Crack(message, sessionId)` it throws the expcetion bellow. According to the debugger the received messages are of type `QuickFix.Message {QuickFix.FIX43.MarketDataSnapshotFullRefresh}`. 

How can I cast this types to each other? Please provide some more documentation for your nuget package. Thanks in advance! 

```
QuickFix.UnsupportedMessageType
  HResult=0x80131500
  Message=Exception of type 'QuickFix.UnsupportedMessageType' was thrown.
  Source=QuickFix
  StackTrace:
   at QuickFix.MessageCracker.Crack(Message message, SessionID sessionID)
   at MyProject.Clients.FixClient.FromApp(Message message, SessionID sessionId) in C:\Dev\Repos\MySolution\MyProject\Clients\FixClient.cs:line 235
   at QuickFix.Session.Verify(Message msg, Boolean checkTooHigh, Boolean checkTooLow)
   at QuickFix.Session.Next(MessageBuilder msgBuilder)
```

When I try to parse the type `QuickFix.FIX43.MarketDataSnapshotFullRefresh` to my generated `MyProject.MarketDataSnapshotFullRefresh` I get the following exception. 

```
System.InvalidCastException
  HResult=0x80004002
  Message=Unable to cast object of type 'QuickFix.FIX43.MarketDataSnapshotFullRefresh' to type 'MyProject.MarketDataSnapshotFullRefresh'.
  Source=MyProject
  StackTrace:
   at MyProject.Clients.FixClient.FromApp(Message message, SessionID sessionId) in C:\Dev\Repos\MySolution\MyProject\Clients\FixClient.cs:line 236
   at QuickFix.Session.Verify(Message msg, Boolean checkTooHigh, Boolean checkTooLow)
   at QuickFix.Session.Next(MessageBuilder msgBuilder)
   at QuickFix.Session.NextMessage(String msgStr)
   at QuickFix.SocketInitiatorThread.ProcessStream()
   at QuickFix.SocketInitiatorThread.Read()
```

**Comment by mickthompson** [comment]
It's been a while since I looked at this, but my guess would be that you aren't passing in the generated MessageFactory to the SocketInitiator constructor.

Best order to run the templates in:
FieldTags, Fields, Messages, MessageFactory

Regarding QuickFix versions, you can see in the packages.config that this was built against 1.5.

**Comment by matthiasguentert** [comment]
Thanks for replying. I indeed forgot to pass in a generated MessageFactory instance to the SocketInitiator constructor. It still works fine with the latest QuickFix.Net version 1.8.0
